name: 'Workflow Duration Action'
description: 'Action to get the duration seconds of the workflow'
inputs:
  url:
    description: 'url of the workflow'
    required: false
outputs:
  duration:
    description: 'duration of the workflow in seconds'
runs:
  using: 'node16'
  main: 'dist/index.js'
