name: 'Workflow Duration Action'
description: 'Action to get the duration seconds of the workflow'
author: 'Chan Nyein Ko Ko'
inputs:
  repository:
    description: 'repository name with owner'
    required: false
    default: ${{ github.event.workflow_run.head_repository.full_name }}
  run_id:
    description: 'run id of the workflow'
    required: false
    default: ${{ github.event.workflow_run.id }}
  github_token:
    description: 'github token'
    required: false
    default: ${{ github.token }}
outputs:
  duration:
    description: 'duration of the workflow in seconds'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'clock'
  color: 'gray-dark'
