name: 'Workflow Duration Action'
description: 'Action to get the duration seconds of the workflow'
inputs:
  owner:
    description: 'owner of the workflow'
    required: false
  repo:
    description: 'repo of the workflow'
    required: false
  run_id:
    description: 'run id of the workflow'
    required: false
  token:
    description: 'github token'
    required: true
outputs:
  duration:
    description: 'duration of the workflow in seconds'
runs:
  using: 'node16'
  main: 'dist/index.js'
